import { NextRequest, NextResponse } from "next/server";
import { isAuthenticated } from "@/lib/auth";
import { Document, Page, View, Text, Font, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import path from "path";

// Register local fonts — verify these paths work on Vercel's read-only filesystem
const fontsDir = path.join(process.cwd(), "public", "fonts");

Font.register({
  family: "Outfit",
  fonts: [
    { src: path.join(fontsDir, "Outfit-Medium.ttf"), fontWeight: 500 },
    { src: path.join(fontsDir, "Outfit-Bold.ttf"), fontWeight: 700 },
  ],
});

Font.register({
  family: "Sora",
  fonts: [
    { src: path.join(fontsDir, "Sora-Regular.ttf"), fontWeight: 400 },
    { src: path.join(fontsDir, "Sora-SemiBold.ttf"), fontWeight: 600 },
  ],
});

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: "#ffffff" },
  header: { fontFamily: "Outfit", fontWeight: 700, fontSize: 24, color: "#F59E0B", marginBottom: 8 },
  subtitle: { fontFamily: "Sora", fontWeight: 400, fontSize: 14, color: "#6B7280", marginBottom: 24 },
  section: { marginBottom: 16 },
  sectionTitle: { fontFamily: "Outfit", fontWeight: 500, fontSize: 16, color: "#1F2937", marginBottom: 6 },
  body: { fontFamily: "Sora", fontWeight: 400, fontSize: 12, color: "#374151", lineHeight: 1.6 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40 },
  footerText: { fontFamily: "Sora", fontWeight: 400, fontSize: 9, color: "#9CA3AF", textAlign: "center" },
});

function TestDocument() {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>PACIFIC FLOW ENTERTAINMENT</Text>
        <Text style={styles.subtitle}>Post-Service Summary — Font Verification Test</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>GUEST ENGAGEMENT</Text>
          <Text style={styles.body}>23 song requests from your guests</Text>
          <Text style={styles.body}>18 songs played (78% response rate)</Text>
          <Text style={styles.body}>Peak engagement: 8:00 - 9:00 PM</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>TOP REQUESTED</Text>
          <Text style={styles.body}>1. Despacito (5 requests)</Text>
          <Text style={styles.body}>2. Besame Mucho (3 requests)</Text>
          <Text style={styles.body}>3. Hotel California (3 requests)</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AUDIENCE VIBES</Text>
          <Text style={styles.body}>Fire: 8 | Energy: 5 | Softer: 3</Text>
        </View>

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by LiveRequest for Pacific Flow Entertainment</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function GET(request: NextRequest) {
  if (!(await isAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const buffer = await renderToBuffer(<TestDocument />);

    return new Response(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="pacific-flow-test.pdf"',
        "X-Content-Type-Options": "nosniff",
      },
    });
  } catch (err) {
    console.error("PDF generation failed:", err);
    return NextResponse.json({ error: "PDF generation failed", details: String(err) }, { status: 500 });
  }
}
