// Auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Replace this file once you have a Supabase project.
// Re-run the command every time the database schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      songs: {
        Row: {
          id: string
          title: string
          artist: string | null
          sort_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          artist?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          artist?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      gigs: {
        Row: {
          id: string
          venue_name: string
          gig_date: string
          is_active: boolean
          requests_open: boolean
          created_at: string
        }
        Insert: {
          id?: string
          venue_name: string
          gig_date: string
          is_active?: boolean
          requests_open?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          venue_name?: string
          gig_date?: string
          is_active?: boolean
          requests_open?: boolean
          created_at?: string
        }
        Relationships: []
      }
      song_requests: {
        Row: {
          id: string
          gig_id: string
          song_id: string
          session_id: string
          created_at: string
        }
        Insert: {
          id?: string
          gig_id: string
          song_id: string
          session_id: string
          created_at?: string
        }
        Update: {
          id?: string
          gig_id?: string
          song_id?: string
          session_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "song_requests_gig_id_fkey"
            columns: ["gig_id"]
            isOneToOne: false
            referencedRelation: "gigs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_requests_song_id_fkey"
            columns: ["song_id"]
            isOneToOne: false
            referencedRelation: "songs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
