// Auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Replace this file once you have a Supabase project.
// Re-run the command every time the database schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      venues: {
        Row: {
          id: string
          name: string
          address: string | null
          notes: string | null
          default_configuration: string | null
          default_genre_style: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          address?: string | null
          notes?: string | null
          default_configuration?: string | null
          default_genre_style?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string | null
          notes?: string | null
          default_configuration?: string | null
          default_genre_style?: string | null
          created_at?: string
        }
        Relationships: []
      }
      performance_sessions: {
        Row: {
          id: string
          gig_id: string
          venue_id: string | null
          set_number: number
          configuration: string
          genre_style: string | null
          status: string
          post_set_data: Json | null
          started_at: string | null
          ended_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          gig_id: string
          venue_id?: string | null
          set_number?: number
          configuration: string
          genre_style?: string | null
          status?: string
          post_set_data?: Json | null
          started_at?: string | null
          ended_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          gig_id?: string
          venue_id?: string | null
          set_number?: number
          configuration?: string
          genre_style?: string | null
          status?: string
          post_set_data?: Json | null
          started_at?: string | null
          ended_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "performance_sessions_gig_id_fkey"
            columns: ["gig_id"]
            isOneToOne: false
            referencedRelation: "gigs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "performance_sessions_venue_id_fkey"
            columns: ["venue_id"]
            isOneToOne: false
            referencedRelation: "venues"
            referencedColumns: ["id"]
          },
        ]
      }
      song_logs: {
        Row: {
          id: string
          session_id: string
          song_id: string | null
          song_title: string | null
          song_quality: string
          volume_calibration: string
          guest_acknowledgment: boolean
          set_position: number
          logged_at: string
        }
        Insert: {
          id?: string
          session_id: string
          song_id?: string | null
          song_title?: string | null
          song_quality: string
          volume_calibration: string
          guest_acknowledgment?: boolean
          set_position: number
          logged_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          song_id?: string | null
          song_title?: string | null
          song_quality?: string
          volume_calibration?: string
          guest_acknowledgment?: boolean
          set_position?: number
          logged_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "song_logs_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "performance_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_logs_song_id_fkey"
            columns: ["song_id"]
            isOneToOne: false
            referencedRelation: "songs"
            referencedColumns: ["id"]
          },
        ]
      }
      songs: {
        Row: {
          id: string
          title: string
          artist: string | null
          sort_order: number
          is_active: boolean
          energy_level: string | null
          repertoire_type: string | null
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          artist?: string | null
          sort_order?: number
          is_active?: boolean
          energy_level?: string | null
          repertoire_type?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          artist?: string | null
          sort_order?: number
          is_active?: boolean
          energy_level?: string | null
          repertoire_type?: string | null
          created_at?: string
        }
        Relationships: []
      }
      gigs: {
        Row: {
          id: string
          venue_name: string
          gig_date: string
          is_active: boolean
          requests_open: boolean
          created_at: string
        }
        Insert: {
          id?: string
          venue_name: string
          gig_date: string
          is_active?: boolean
          requests_open?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          venue_name?: string
          gig_date?: string
          is_active?: boolean
          requests_open?: boolean
          created_at?: string
        }
        Relationships: []
      }
      song_requests: {
        Row: {
          id: string
          gig_id: string
          song_id: string
          session_id: string
          created_at: string
          played_at: string | null
          vibe: string | null
        }
        Insert: {
          id?: string
          gig_id: string
          song_id: string
          session_id: string
          created_at?: string
          played_at?: string | null
          vibe?: string | null
        }
        Update: {
          id?: string
          gig_id?: string
          song_id?: string
          session_id?: string
          created_at?: string
          played_at?: string | null
          vibe?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "song_requests_gig_id_fkey"
            columns: ["gig_id"]
            isOneToOne: false
            referencedRelation: "gigs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "song_requests_song_id_fkey"
            columns: ["song_id"]
            isOneToOne: false
            referencedRelation: "songs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      insert_song_log: {
        Args: {
          p_session_id: string
          p_song_id: string | null
          p_song_title: string | null
          p_song_quality: string
          p_volume_calibration: string
          p_guest_acknowledgment: boolean
        }
        Returns: {
          id: string
          session_id: string
          song_id: string | null
          song_title: string | null
          song_quality: string
          volume_calibration: string
          guest_acknowledgment: boolean
          set_position: number
          logged_at: string
        }
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
